# Generated by Django 4.2.7 on 2023-11-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Prayer Date')),
                ('prayer', models.CharField(choices=[('P', 'Prosperity'), ('F', 'Food'), ('S', 'Safety')], default='P', max_length=1)),
                ('mythology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mythology')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
